// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: servletrpc.proto

package org.xy9.protobufservletrpc.lib;

public final class ServletRpcProtos {
  private ServletRpcProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface ServiceRequestOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required int32 method_id = 1;
    boolean hasMethodId();
    int getMethodId();
    
    // required bytes arguments = 2;
    boolean hasArguments();
    com.google.protobuf.ByteString getArguments();
  }
  public static final class ServiceRequest extends
      com.google.protobuf.GeneratedMessage
      implements ServiceRequestOrBuilder {
    // Use ServiceRequest.newBuilder() to construct.
    private ServiceRequest(Builder builder) {
      super(builder);
    }
    private ServiceRequest(boolean noInit) {}
    
    private static final ServiceRequest defaultInstance;
    public static ServiceRequest getDefaultInstance() {
      return defaultInstance;
    }
    
    public ServiceRequest getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.xy9.protobufservletrpc.lib.ServletRpcProtos.internal_static_ServiceRequest_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.xy9.protobufservletrpc.lib.ServletRpcProtos.internal_static_ServiceRequest_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required int32 method_id = 1;
    public static final int METHOD_ID_FIELD_NUMBER = 1;
    private int methodId_;
    public boolean hasMethodId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public int getMethodId() {
      return methodId_;
    }
    
    // required bytes arguments = 2;
    public static final int ARGUMENTS_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString arguments_;
    public boolean hasArguments() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public com.google.protobuf.ByteString getArguments() {
      return arguments_;
    }
    
    private void initFields() {
      methodId_ = 0;
      arguments_ = com.google.protobuf.ByteString.EMPTY;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasMethodId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasArguments()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, methodId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, arguments_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, methodId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, arguments_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static org.xy9.protobufservletrpc.lib.ServletRpcProtos.ServiceRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static org.xy9.protobufservletrpc.lib.ServletRpcProtos.ServiceRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static org.xy9.protobufservletrpc.lib.ServletRpcProtos.ServiceRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static org.xy9.protobufservletrpc.lib.ServletRpcProtos.ServiceRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static org.xy9.protobufservletrpc.lib.ServletRpcProtos.ServiceRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static org.xy9.protobufservletrpc.lib.ServletRpcProtos.ServiceRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static org.xy9.protobufservletrpc.lib.ServletRpcProtos.ServiceRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static org.xy9.protobufservletrpc.lib.ServletRpcProtos.ServiceRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static org.xy9.protobufservletrpc.lib.ServletRpcProtos.ServiceRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static org.xy9.protobufservletrpc.lib.ServletRpcProtos.ServiceRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(org.xy9.protobufservletrpc.lib.ServletRpcProtos.ServiceRequest prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements org.xy9.protobufservletrpc.lib.ServletRpcProtos.ServiceRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.xy9.protobufservletrpc.lib.ServletRpcProtos.internal_static_ServiceRequest_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.xy9.protobufservletrpc.lib.ServletRpcProtos.internal_static_ServiceRequest_fieldAccessorTable;
      }
      
      // Construct using org.xy9.protobufservletrpc.lib.ServletRpcProtos.ServiceRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        methodId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        arguments_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.xy9.protobufservletrpc.lib.ServletRpcProtos.ServiceRequest.getDescriptor();
      }
      
      public org.xy9.protobufservletrpc.lib.ServletRpcProtos.ServiceRequest getDefaultInstanceForType() {
        return org.xy9.protobufservletrpc.lib.ServletRpcProtos.ServiceRequest.getDefaultInstance();
      }
      
      public org.xy9.protobufservletrpc.lib.ServletRpcProtos.ServiceRequest build() {
        org.xy9.protobufservletrpc.lib.ServletRpcProtos.ServiceRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private org.xy9.protobufservletrpc.lib.ServletRpcProtos.ServiceRequest buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        org.xy9.protobufservletrpc.lib.ServletRpcProtos.ServiceRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public org.xy9.protobufservletrpc.lib.ServletRpcProtos.ServiceRequest buildPartial() {
        org.xy9.protobufservletrpc.lib.ServletRpcProtos.ServiceRequest result = new org.xy9.protobufservletrpc.lib.ServletRpcProtos.ServiceRequest(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.methodId_ = methodId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.arguments_ = arguments_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.xy9.protobufservletrpc.lib.ServletRpcProtos.ServiceRequest) {
          return mergeFrom((org.xy9.protobufservletrpc.lib.ServletRpcProtos.ServiceRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(org.xy9.protobufservletrpc.lib.ServletRpcProtos.ServiceRequest other) {
        if (other == org.xy9.protobufservletrpc.lib.ServletRpcProtos.ServiceRequest.getDefaultInstance()) return this;
        if (other.hasMethodId()) {
          setMethodId(other.getMethodId());
        }
        if (other.hasArguments()) {
          setArguments(other.getArguments());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasMethodId()) {
          
          return false;
        }
        if (!hasArguments()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              methodId_ = input.readInt32();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              arguments_ = input.readBytes();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required int32 method_id = 1;
      private int methodId_ ;
      public boolean hasMethodId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public int getMethodId() {
        return methodId_;
      }
      public Builder setMethodId(int value) {
        bitField0_ |= 0x00000001;
        methodId_ = value;
        onChanged();
        return this;
      }
      public Builder clearMethodId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        methodId_ = 0;
        onChanged();
        return this;
      }
      
      // required bytes arguments = 2;
      private com.google.protobuf.ByteString arguments_ = com.google.protobuf.ByteString.EMPTY;
      public boolean hasArguments() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public com.google.protobuf.ByteString getArguments() {
        return arguments_;
      }
      public Builder setArguments(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        arguments_ = value;
        onChanged();
        return this;
      }
      public Builder clearArguments() {
        bitField0_ = (bitField0_ & ~0x00000002);
        arguments_ = getDefaultInstance().getArguments();
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:ServiceRequest)
    }
    
    static {
      defaultInstance = new ServiceRequest(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:ServiceRequest)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_ServiceRequest_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_ServiceRequest_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020servletrpc.proto\"6\n\016ServiceRequest\022\021\n\t" +
      "method_id\030\001 \002(\005\022\021\n\targuments\030\002 \002(\014B2\n\036or" +
      "g.xy9.protobufservletrpc.libB\020ServletRpc" +
      "Protos"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_ServiceRequest_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_ServiceRequest_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_ServiceRequest_descriptor,
              new java.lang.String[] { "MethodId", "Arguments", },
              org.xy9.protobufservletrpc.lib.ServletRpcProtos.ServiceRequest.class,
              org.xy9.protobufservletrpc.lib.ServletRpcProtos.ServiceRequest.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
